# Generated by Django 2.1.7 on 2019-02-27 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipInfo',
            fields=[
                ('imo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ship_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoInfo1',
            fields=[
                ('imo_id_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='GeoPosApp.ShipInfo')),
                ('position_timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15)),
            ],
        ),
    ]
