# Generated by Django 2.1.7 on 2019-02-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoPosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geoinfo1',
            old_name='imo_id_id',
            new_name='imo',
        ),
    ]
