# Generated by Django 2.1.7 on 2019-02-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoPosApp', '0002_auto_20190227_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoinfo1',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geoinfo1',
            name='imo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeoPosApp.ShipInfo'),
        ),
    ]
